language: php

branches:
  only:
    - /.*/

php:
  - '7.4'

before_install:
  - phpenv config-rm xdebug.ini || return 0

install:
  - composer self-update
  - composer install --no-interaction

before_script:
  - mkdir build
  - mkdir test-resources/attachments/dir/dirdept

script:
  - composer ci

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
